# [price, score[Brand, Design, Display, Software, Camera, Performance, Battery], Pros:['','',''], Cons:['','','']]
information = {
    'IphoneX':[80000, [5, 5, 5, 5, 5, 5, 4], ['display','bezel-less','camera', 'latest'], ['battery', 'expensive'],'Iphone X','https://www.91mobiles.com/apple-iphone-x-price-in-india'],
    'Iphone8':[50000, [5, 4, 4, 5, 4, 5, 3], ['camera', 'performance', 'display', 'latest'], ['battery', 'expensive'],'Iphone 8','https://www.91mobiles.com/apple-iphone-8-price-in-india'],
    'Iphone7':[38500, [5, 4, 4, 5, 4, 4, 3],
    ['camera', 'performance', 'display'], ['storage', 'expensive'],'Iphone7','https://www.91mobiles.com/apple-iphone-7-price-in-india'],
    'IphoneSE':[18000, [5, 3, 3, 5, 3, 4, 3],
    ['compact','',''], ['','',''],'Iphone SE','https://www.91mobiles.com/apple-iphone-5se-price-in-india'],
    'Iphone6s':[32000, [5, 4, 3, 4, 3, 4, 3],
    ['','',''], ['battery'],'Iphone 6S','https://www.91mobiles.com/apple-iphone-6s-price-in-india'],
    'Pixel2':[47000, [4, 4, 4, 5, 5, 5, 4],
    ['camera', 'performance', 'latest'], ['display'],'Pixel 2','https://www.91mobiles.com/google-pixel-2-price-in-india'],
    'Pixel':[28000, [4, 4, 4, 5, 4, 4, 4],
    ['camera', 'performance', 'display'], ['storage'],'Pixel','https://www.91mobiles.com/google-pixel-price-in-india'],
    'GalaxyS8':[44000, [4, 4, 4, 3, 4, 5, 3],
    ['camera', 'performance', 'display'], ['battery', 'expensive'],'Galaxy S8','https://www.91mobiles.com/samsung-galaxy-s8-price-in-india'],
    'GalaxyNote8':[57000, [4, 4, 4, 5, 4, 5, 3],
    ['camera', 'performance', 'display'], ['battery', 'expensive'],'Galaxy Note 8','https://www.91mobiles.com/samsung-galaxy-note-8-price-in-india'],
    'GalaxyA8+':[30000, [4, 3, 3, 5, 4, 5, 3],
    ['camera', 'performance', 'display'], ['battery', 'expensive'],'Galaxy A8+','https://www.91mobiles.com/samsung-galaxy-a8-plus-2018-price-in-india'],
    'GalaxyC9Pro':[28000, [4, 3, 3, 5, 4, 5, 3],
    ['camera', 'storage',''], ['battery', 'expensive'],'Galaxy C9 Pro','https://www.91mobiles.com/samsung-galaxy-c9-pro-price-in-india'],
    'GalaxyC7':[29000, [4, 3, 3, 5, 4, 5, 3],
    ['camera', 'latest',''], ['expensive'],'Galaxy C7','https://www.91mobiles.com/samsung-galaxy-c7-pro-price-in-india'],
    'GalaxyJ7':[14800, [4, 2, 2, 3, 4, 4, 4],
    ['battery', 'camera',''], ['','',''],'Galaxy J7','https://www.91mobiles.com/samsung-galaxy-j7-price-in-india'],
    'GalaxyJ5':[16000, [4, 3, 3, 3, 4, 4, 4],
    ['battery', 'camera',''], ['expensive'],'Galaxy J5','https://www.91mobiles.com/samsung-galaxy-j5-price-in-india'],
    'GalaxyOn7Prime':[14000, [4, 3, 3, 3, 3, 5, 4],
    ['display', 'latest',''], ['expensive'],'Galaxy On7 Prime','https://www.91mobiles.com/samsung-galaxy-on7-prime-64gb-price-in-india'],
    'GalaxyJ2Pro':[7499, [4, 3, 3, 3, 2, 2, 3],
    ['display'], ['','',''],'Galaxy J2 Pro','https://www.91mobiles.com/samsung-galaxy-j2-pro-2018-price-in-india'],
    'GalaxyS7Edge':[35890, [4, 4, 4, 3, 4, 5, 4],
    ['display',], ['expensive', 'software'],'Galaxy S7 Edge','https://www.91mobiles.com/samsung-galaxy-s7-edge-price-in-india'],
    'GalaxyS9':[57900, [4, 4, 4, 3, 5, 5, 4],
    ['display', 'latest', 'wireless charging',], ['software'],'Galaxy S9','https://www.91mobiles.com/samsung-galaxy-s9-price-in-india'],
    'OnePlus5T':[37999, [3, 4, 4, 4, 5, 5, 4],
    ['display', 'latest', 'camera', 'battery'], ['software'],'One Plus 5T','https://www.91mobiles.com/oneplus-5t-price-in-india'],
    'OnePlus5':[32999, [3, 4, 4, 3, 5, 5, 4],
    ['display', 'latest', 'camera', 'battery'], ['software'],'One Plus 5','https://www.91mobiles.com/oneplus-5-price-in-india'],
    'HTCU11':[45999, [3, 4, 4, 3, 4, 4, 3],
    ['dual-sim', 'latest', 'quick charging',], ['internal storage'],'HTC U11','https://www.91mobiles.com/htc-11-price-in-india'],
    'HTCU':[25191, [3, 4, 4, 4, 4, 4, 4],
    ['battery', 'camera', 'display'], ['','',''],'HTC U','https://www.91mobiles.com/htc-u-ultra-price-in-india'],
    'HTCDesire10':[16490, [3, 3, 3, 3, 3, 3, 4],
    ['dual-sim', 'front-flash', 'expandable memory',], ['','',''],'HTC Desire 10','https://www.91mobiles.com/htc-desire-10-pro-price-in-india'],
    'HTC10Lifestyle':[19990, [3, 4, 4, 3, 4, 4, 4],
    ['metallic body', 'camera', 'expandable memory', 'display'], ['single sim', 'heavy'],'HTC 10 Lifestyle','https://www.91mobiles.com/htc-10-lifestyle-price-in-india'],
    'HTCDesire630':[8099, [3, 3, 3, 3, 3, 2, 3],
    ['camera', 'value for money',''], ['battery'],'HTC Desire 630','https://www.91mobiles.com/htc-desire-630-price-in-india'],
    'RedmiNote5':[12000,[3,4,3,4,3,4,4],['configuration','cost','camera','battery'],['','',''],'Redmi Note 5','https://www.91mobiles.com/xiaomi-redmi-note-5-price-in-india'],
    'MiMix2':[33000,[2,4,3,4,4,5,4],['configuration','camera','display','charging'],['memory fixed'],'Mi Mix 2','https://www.91mobiles.com/xiaomi-mi-mix-2s-price-in-india'],
    'RedmiNote4':[11000,[2,3,3,3,3,4,4],['configuration','battery','system space','camera'],['hybrid-sim','Non-removable battery'],'Redmi Note 4','https://www.91mobiles.com/xiaomi-redmi-note-4-64gb-price-in-india'],
    'Redmi4':[8000,[2,3,3,3,3,4,4],['display','performance','body','battery'],['hybrid-sim','Non-removable battery'],'Redmi 4','https://www.91mobiles.com/xiaomi-redmi-4-32gb-price-in-india'],
    'MiMax2':[15000,[2,3,3,4,3,4,5],['display','processor','charging','camera','battery'],['Non-removable battery','hybrid-sim'],'Mi Max 2','https://www.91mobiles.com/xiaomi-mi-max-2-price-in-india'],
    'XiaomiMiA1':[15000,[2,3,3,4,3,4,4],['Design','camera','configuration'],['battery'],'Xiaomi Mi A1','https://www.91mobiles.com/xiaomi-mi-a1-price-in-india'],
    'Nokia8':[26000,[4,3,4,4,4,4,4],['configuration','camera','storage','charging'],['Non-removable battery','fixed memory'],'Nokia 8','https://www.91mobiles.com/nokia-8-price-in-india'],
    'Nokia6':[13000,[4,3,3,4,3,4,4],['configuration','camera','storage'],[' battery'],'Nokia 6','https://www.91mobiles.com/nokia-6-price-in-india'],
    'MotoZ2Force':[35000,[4,4,4,5,4,4,4],['configuration','charging','display','screen','camera'],['Non-removable battery'],'Moto Z2 Force','https://www.91mobiles.com/moto-z2-force-price-in-india'],
    'MotoG5Plus':[14000,[4,3,3,4,4,4,4],['configuration','display','camera','front flash'],['storage','battery'],'Moto G5 Plus','https://www.91mobiles.com/moto-g5-plus-price-in-india'],
    'MotoX4':[21000,[4,3,3,4,4,4,4],['configuration','camera','Design','water resistance'], ['','',''],'MotoX4','https://www.91mobiles.com/moto-x4-price-in-india'],
    'MotoG5s':[13000,[4,3,3,4,4,4,4],['configuration','charging','camera'],['Non-removable battery'],'Moto G5 S','https://www.91mobiles.com/moto-g5s-price-in-india'],
    'MotoE4Plus':[9000,[4,3,3,4,3,3,4],['battery','charging',''],['heavy'],'Moto E4 Plus','https://www.91mobiles.com/moto-e4-plus-32gb-price-in-india'],
    'MotoE4':[9000,[4,3,3,4,3,3,4],['battery','charging',''],['heavy'],'Moto E4','https://www.91mobiles.com/moto-e4-price-in-india'],
    'MotoZ2Play':[19000,[4,3,4,4,4,4,4],['charging','configuration','glass'], ['','',''],'Moto Z2 Play','https://www.91mobiles.com/moto-z2-play-price-in-india'],
    'MotoG5':[8000,[4,3,3,4,3,3,4],['battery','camera','configuration','charging'],['thick','heavy'],'Moto G5','https://www.91mobiles.com/moto-g5-price-in-india'],
    'MotoZ':[21000,[4,3,4,4,4,4,4],['configuration','slim body','charging'],['single-sim'],'Moto Z','https://www.91mobiles.com/moto-z-play-32gb-price-in-india'],
    'MotoM':[12000,[4,3,3,4,3,4,4],['configuration','fingerprint','battery','camera'],['single-sim'],'MotoM','https://www.91mobiles.com/moto-m-price-in-india'],
    'MotoC':[6000,[4,3,3,4,3,3,4],['battery','front flash',''], ['','',''],'MotoC','https://www.91mobiles.com/moto-c-plus-price-in-india'],
    'Honor7X':[12400,[3,3,3,4,3,4,4],['configuration','battery','camera'],['hybrid-sim'],'Honor 7X','https://www.91mobiles.com/honor-7x-price-in-india'],
    'Honor9i':[26000,[3,3,3,4,3,4,4],['','',''],['','',''],'Honor9i','https://www.91mobiles.com/honor-9i-price-in-india'],
    'Honor9':[14000,[3,3,3,5,3,4,4],['display','performance','camera'],['battery'],'Honor 9','https://www.91mobiles.com/honor-9-price-in-india'],
    'Honor8':[15000,[3,4,3,3,3,4,4],['display','performance','camera','storage','charging'],['battery','hybrid-sim'],'Honor 8','https://www.91mobiles.com/honor-8-price-in-india'],
    'Honor8Pro':[26000,[3,4,4,4,3,4,4],['RAM','camera','storage','quick charge'], ['','',''],'Honor 8 Pro','https://www.91mobiles.com/honor-8-pro-price-in-india'],
    'LGV30':[45000,[3,4,4,4,3,4,4],['display','water resistance','camera','configuration','storage'],['front-camera'],'LG V30','https://www.91mobiles.com/lg-v30-price-in-india'],
    'LGG6':[30000,[3,4,4,4,5,4,4],['waterproof','configuration','display'],['single-sim'],'LG G6','https://www.91mobiles.com/lg-g6-price-in-india'],
    'LGQ6':[12000,[3,4,3,4,3,3,4],['configuration','camera','battery',],['Non-removable battery'],'LG Q6','https://www.91mobiles.com/lg-q6-price-in-india'],
    'SonyXperiaZ5':[28000,[4,3,3,3,3,4,4],['camera','battery','processor','memory'],['front-camera','expensive'],'Sony Xperia Z5','https://www.91mobiles.com/sony-xperia-z5-dual-price-in-india'],
    'SonyXperiaXZ':[31000,[4,4,3,4,3,4,4],['configuration','camera','water resistance','charging'],['compass','gyroscope','Non-removable battery'],'Sony Xperia XZ','https://www.91mobiles.com/sony-xperia-xz-price-in-india'],
    'SonyXperiaR1':[9000,[4,3,3,4,3,3,4],['processor','storage','battery'],['Non-removable battery'],'Sony Xperia R1','https://www.91mobiles.com/sony-xperia-r1-price-in-india'],
    'SonyXperiaXA1Dual':[15527,[4,3,3,4,3,4,3],['quick charge','processor','performance','camera','storage'],['Non-removable battery','Expensive','battery'],'Sony Xperia XA1 Dual','https://www.91mobiles.com/sony-xperia-xa1-price-in-india'],
}
