# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('goa', 'Goa'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore')], default='goa', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=1000)),
                ('certificates', models.URLField(default='null')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
