# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_m',
            name='budget',
            field=models.CharField(choices=[('Less than 5000', 'Less than 5000'), ('Less than 10000', 'Less than 10000'), ('Less than 20000', 'Less than 20000'), ('Less than 50000', 'Less than 50000'), ('No constraint', 'No constraint')], default='No constraint', max_length=100),
        ),
    ]
