# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0002_question_m_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_m',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='item',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='price',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='quantity',
        ),
        migrations.AddField(
            model_name='question_m',
            name='age',
            field=models.CharField(choices=[('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40+', '40+')], default='20-30', max_length=100),
        ),
        migrations.AddField(
            model_name='question_m',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='question_m',
            name='prefer_to_chinese',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='question_m',
            name='profession',
            field=models.CharField(choices=[('IT', 'IT'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('BusinessMan', 'BuisnessMan')], default='IT', max_length=100),
        ),
        migrations.AddField(
            model_name='question_m',
            name='task',
            field=models.CharField(choices=[('Battery Life', 'Battery Life'), ('Camera', 'Camera')], default='Camera', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_m',
            name='location',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
    ]
