# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-18 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0003_auto_20180317_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_m',
            name='majoruse',
            field=models.CharField(choices=[('Calling', 'Calling'), ('Photography', 'Photography'), ('Gaming', 'Gaming'), ('Whatsapp', 'Whatsapp'), ('Movie', 'Movie')], default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='question_m',
            name='size',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_m',
            name='budget',
            field=models.CharField(choices=[('5000', '5000'), ('10000', '10000'), ('15000', '15000'), ('20000', '20000'), ('40000', '40000'), ('Flagship', 'Flagship')], default='No constraint', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_m',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Business', 'Buisness'), ('Elderly Person', 'Elderly Person')], default='IT', max_length=100),
        ),
    ]
