# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-18 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0004_auto_20180318_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_m',
            name='majoruse',
        ),
    ]
